FROM williamyeh/ansible:centos7
MAINTAINER Shaun Martin <shaun@samsite.ca>

VOLUME /data
VOLUME /results

ENV RESULTS_FILE /results/centos7
ENV PLAYBOOK /data/test.yml

COPY . /data/

COPY test/ansible-playbook-wrapper /usr/local/bin/
RUN ansible-playbook-wrapper -vvv

COPY test/checks.sh /usr/local/bin/

CMD ["/usr/local/bin/checks.sh"]
